-- MySQL Script generated by MySQL Workbench
-- jeu. 23 févr. 2017 13:57:50 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amis` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `description` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `date_naissance` DATETIME NULL,
  `pays` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `prenom_nom` VARCHAR(45) NULL,
  `id_compte` INT NULL,
  `age` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`id`, `id_utilisateur`),
  INDEX `fk_compte_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_compte_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_message` VARCHAR(45) NULL,
  `id_mur` INT NULL,
  `id_utilisateur` INT NOT NULL,
  `message` VARCHAR(255) NULL,
  `heure` DATETIME NULL,
  PRIMARY KEY (`id`, `id_utilisateur`),
  INDEX `fk_mur_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_mur_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentaire` VARCHAR(255) NULL,
  `heure` VARCHAR(45) NULL,
  `id_utilisateur` INT NOT NULL,
  `id_mur` INT NOT NULL,
  PRIMARY KEY (`id`, `id_utilisateur`, `id_mur`),
  INDEX `fk_commentaire_utilisateur1_idx` (`id_utilisateur` ASC),
  INDEX `fk_commentaire_mur1_idx` (`id_mur` ASC),
  CONSTRAINT `fk_commentaire_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_mur1`
    FOREIGN KEY (`id_mur`)
    REFERENCES `mydb`.`mur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
